### ISSUE TITLE
Suru++ Dark is officially released

### ISSUE THREAD

**Issue by gusbemacbe** [gusbemacbe/suru-plus-dark#2]
Hello @Feichtmeier, @ramzydoni, @vaskark and @venorz!

Good morning!

The Suru++ dark icons theme is officially released after a month of alpha and beta. You can download the source code.

The PPA will be soon fixed. And the Suru++ Dark United will be soon released after the school break.

**Comment by Feichtmeier** [comment]
Great - I really like your work! Ty!

**Comment by gusbemacbe** [comment]
You are welcome!

**Comment by gusbemacbe** [comment]
Hello @Feichtmeier, @ramzydoni, @vaskark and @venorz!

As Suru++ 25 became complete and has 5,2k icons and new 14 folders colours now, I upgraded Suru++ Dark, renaming to Suru++ 25 Dark.

**Comment by materemias** [comment]
@gusbemacbe amazing work, thanks for this, do you plan to somehow get this part of the big suru-plus repository? or do you have an easier way to get this updated?
