### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by gusbemacbe** [gusbemacbe/suru-plus-dark#4]
Hello @SmartFinn!

I enabled this repository to Travis CI, modified the `travis.yml`, but I am unable of triggering build to the branch [`beta`](https://github.com/gusbemacbe/suru-plus-dark/tree/beta) of Suru++ Dark.

**Comment by SmartFinn** [comment]
@gusbemacbe the .travis.yml should be placed into the default branch (master).

**Comment by gusbemacbe** [comment]
@SmartFinn !

I have replaced `Suru++ Dark` for `Suru++-Dark`, it has been fixed without errors according to Travis CI, but is it possible to keep the original name `Suru++ Dark` and to get no errors in Travis CI?

**Comment by SmartFinn** [comment]
@gusbemacbe I don't know how to rewrite the test to ignore the parent dir.

```Makefile
.PHONY: test_filenames
test_filenames:
    # >>> Searching for invalid filenames
    @find $(ICON_THEMES) -not -iregex '[-_/\.+@a-z0-9]+' -print \
        -exec false '{}' + 
```

You could delete it from test task, but I don't recommend do it.

**Comment by gusbemacbe** [comment]
@SmartFinn , too bad, thank you for your counsel! I keep the hyphen.
