### ISSUE TITLE
New Blue tone for folders

### ISSUE THREAD

**Issue by AdsonCicilioti** [gusbemacbe/suru-plus-dark#6]
![image](https://user-images.githubusercontent.com/6278398/52895318-c4090f80-319f-11e9-9351-91b07cad8d38.png)

**Comment by gusbemacbe** [comment]
Hello @AdsonCicilioti,

I do no understand. Are you suggesting me to add new folders colour? Actually it is indigo, not blue.

**Comment by AdsonCicilioti** [comment]
Hi @gusbemacbe,

yep, indigo or a tone more dark or with purple additive.

**Comment by gusbemacbe** [comment]
OK, I will add them in the beta branch and must release on weekend.

**Comment by gusbemacbe** [comment]
@AdsonCicilioti, added to [Suru++](/gusbemacbe/suru-plus), then I will upgrade it to Suru++ Dark.

**Comment by gusbemacbe** [comment]
@AdsonCicilioti, ready!
